CREATE TABLE BRANCH SUPPLIER(
branch_id INTEGER PRIMARY KEY,
supplier_name TEXT NOT NULL,
supply_type TEXT NOT NULL
);



INSERT INTO BRANCH SUPPLIER VALUES(0002,'Hammer Mill','Paper');
INSERT INTO BRANCH SUPPLIER VALUES(0002,'Uni-ball','Writing Utensils');
INSERT INTO BRANCH SUPPLIER VALUES(0003,'Patriot Paper','Paper');
INSERT INTO BRANCH SUPPLIER VALUES(0002,'J.T Form&Lables','Custom Forms');
INSERT INTO BRANCH SUPPLIER VALUES(0003,'Uni-ball','Writting Utensil');
INSERT INTO BRANCH SUPPLIER VALUES(0003,'Hammer Mills','Paper');
INSERT INTO BRANCH SUPPLIER VALUES(0003,'Stamford Labies','Custom Form');

SELECT * FROM BRANCH SUPPLIER