--create
CREATE TABLE CLIENT(
client_id INTEGER PRIMARY KEY,
client_name TEXT NOT NULL,
branch_id INTEGER
);


--INSERT
INSERT INTO CLIENT VALUES (000400,'Dumore Highschool',2);
INSERT INTO CLIENT VALUES (000401,'Lackawana',2);
INSERT INTO CLIENT VALUES (000402, 'FedEx',3);
INSERT INTO CLIENT VALUES (000403, 'John Daly Law LLC', 3);
INSERT INTO CLIENT VALUES (000404, 'Scranton Whitepages',2);
INSERT INTO CLIENT VALUES (000405, 'Times Newspaper',3);
INSERT INTO CLIENT VALUES (000406,'FedEx',2);
SELECT*FROM CLIENT 



